version: "3"

services:
  postgres_db:
    image: postgres:12.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=course_4
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - pg_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  # pgadmin-compose:
  #   image: dpage/pgadmin4
  #   environment:
  #       PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
  #       PGADMIN_DEFAULT_PASSWORD: "test123!"
  #   ports:
  #       - "16543:80"
  #   depends_on:
  #       - postgres_db

volumes:
  pg_data:
